table 'public manutencoes'
	lineageTag: 2ce25130-bba7-45ea-a5db-9c389522171d

	column id_manutencao
		dataType: int64
		formatString: 0
		lineageTag: 86909362-bc78-464e-a348-10bed24e7d67
		summarizeBy: sum
		sourceColumn: id_manutencao

		annotation SummarizationSetBy = Automatic

	column id_parque
		dataType: int64
		formatString: 0
		lineageTag: aa1f6948-0833-4eaa-abb4-401ccfbd0b3e
		summarizeBy: none
		sourceColumn: id_parque

		annotation SummarizationSetBy = Automatic

	column data_inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: 1484f775-a8a6-45b5-9ef4-6e518a15ff68
		summarizeBy: none
		sourceColumn: data_inicio

		variation Variation
			isDefault
			relationship: edfcb65a-6c0c-4da7-96e7-733a531ea40d
			defaultHierarchy: LocalDateTable_a05e8cfa-36d0-4a14-a85e-ed66e31e234d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_fim
		dataType: dateTime
		formatString: General Date
		lineageTag: d7488e2e-f762-43bb-8790-b6899008ccab
		summarizeBy: none
		sourceColumn: data_fim

		variation Variation
			isDefault
			relationship: 888dc433-3e13-4bf9-9341-56d4ddc93098
			defaultHierarchy: LocalDateTable_5caddd9d-727b-4d3c-8f88-8b7e3ccb71c5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Tipos de Manutenção'
		dataType: string
		lineageTag: a1fed09b-af46-43a3-ba12-c8c1e9290e6c
		summarizeBy: none
		sourceColumn: Tipos de Manutenção

		annotation SummarizationSetBy = Automatic

	column custo_manutencao
		dataType: double
		lineageTag: 3d045d53-1d46-422f-b4cf-bdb5f4a94e18
		summarizeBy: sum
		sourceColumn: custo_manutencao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column horas_parado
		dataType: int64
		formatString: 0
		lineageTag: 2aff9ff2-5a8c-40ac-b513-5ecc41a912fb
		summarizeBy: sum
		sourceColumn: horas_parado

		annotation SummarizationSetBy = Automatic

	partition 'public manutencoes' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("ep-frosty-heart-adk5skqh-pooler.c-2.us-east-1.aws.neon.tech", "alianca_energia_db"),
				    public_manutencoes = Fonte{[Schema="public",Item="manutencoes"]}[Data],
				    #"Colunas Renomeadas" = Table.RenameColumns(public_manutencoes,{{"tipo_manutencao", "Tipos de Manutenção"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

